"""Init

Revision ID: 054318538ff3
Revises: 
Create Date: 2020-01-27 15:22:22.741327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054318538ff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('places_count', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lic_plate', sa.VARCHAR(length=16), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['owner_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(precision=10, asdecimal=True), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('current_car_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['current_car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('finished',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('issued', sa.DateTime(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('taken', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    # sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    # sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('issued', sa.DateTime(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('taken', sa.DateTime(), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    # sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    # sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('issued', sa.DateTime(), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    # sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=False),
    sa.Column('y1', sa.Integer(), nullable=False),
    sa.Column('x2', sa.Integer(), nullable=False),
    sa.Column('y2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fare_bases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare_bases',
    sa.Column('fare_base_id', sa.INTEGER(), nullable=False),
    sa.Column('price_km', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('fare_base_id', name='sys_c003943598')
    )
    op.drop_table('routes')
    op.drop_table('riders')
    op.drop_table('orders')
    op.drop_table('jobs')
    op.drop_table('finished')
    op.drop_table('drivers')
    op.drop_table('cars')
    # ### end Alembic commands ###
