"""Add Car and car_id to Driver.

Revision ID: 642b246ac41a
Revises: 7d48dfaed31b
Create Date: 2020-01-25 17:29:17.110873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642b246ac41a'
down_revision = '7d48dfaed31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('places_count', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lic_plate', sa.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drivers', sa.Column('car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'car_id')
    op.drop_table('cars')
    # ### end Alembic commands ###
