"""Add price column to finished jobs

Revision ID: a565d52a9a66
Revises: a68321f83ca1
Create Date: 2020-01-26 16:56:49.718059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a565d52a9a66'
down_revision = 'a68321f83ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finished', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finished', 'price')
    # ### end Alembic commands ###
