"""Add current car id

Revision ID: e8f1aeabb1df
Revises: a565d52a9a66
Create Date: 2020-01-27 02:01:26.696360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f1aeabb1df'
down_revision = 'a565d52a9a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('current_car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'cars', ['current_car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'current_car_id')
    # ### end Alembic commands ###
