"""Try FK

Revision ID: eca71819cf1d
Revises: 0342c138dea1
Create Date: 2020-01-27 15:14:03.055436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca71819cf1d'
down_revision = '0342c138dea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cars', 'drivers', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'drivers', 'cars', ['current_car_id'], ['id'])
    op.create_foreign_key(None, 'finished', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'finished', 'riders', ['rider_id'], ['id'])
    op.create_foreign_key(None, 'finished', 'routes', ['route_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'routes', ['route_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'riders', ['rider_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'routes', ['route_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'riders', ['rider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'finished', type_='foreignkey')
    op.drop_constraint(None, 'finished', type_='foreignkey')
    op.drop_constraint(None, 'finished', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    # ### end Alembic commands ###
